version: "3"
services:
  reverseproxy:
    build:
      context: . 
    image: aristidesama/reverseproxy 
  backend_user:
    build:
      context: ../../udacity-c3-restapi-user
    image: aristidesama/udacity-restapi-user
  backend_feed:
    build:
      context: ../../udacity-c3-restapi-feed 
    image: aristidesama/udacity-restapi-feed
  frontend:
    build:
      context: ../../udacity-c3-frontend 
    image: aristidesama/udacity-frontend
