apiVersion: apps/v1
kind: Deployment
metadata:
  labels: 
    service: backend-feed
  name: backend-feed
spec:
        #Sans volumes et volumeMount
  replicas: 3
  selector:
    matchLabels:
      service: backend-feed
  template:
    metadata:
      labels:
        service: backend-feed
    spec:
#      volumes:
#        - name: config-volume
#          configMap:
#            name: env-config
      containers:
      - image: aristidesama/udacity-restapi-feed
        name: backend-feed
        imagePullPolicy: Always
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "1024Mi"
            cpu: "500m"
        env:
        - name: AWS_BUCKET
          valueFrom:
            configMapKeyRef:
              name: env-config
              key: AWS_BUCKET
        - name: AWS_PROFILE
          value: default
        - name: AWS_REGION
          value: us-east-2
        - name: JWT_SECRET
          value: azerty
        - name: POSTGRESS_DB
          value: udagramkomidev
        - name: POSTGRESS_HOST
          value: udagramkomidev.ceace7zxoczq.us-east-2.rds.amazonaws.com
        - name: POSTGRESS_PASSWORD
          value: udagramkomidev
        - name: POSTGRESS_USERNAME
          value: udagramkomidev
#        volumeMounts:
#        - name: config-volume
#          mountPath: /etc/config
#          readOnly: true
      restartPolicy: Always
